version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/StormDetection
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/install.sh
      timeout: 3600
      runas: root
