language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

before_script:
  - sudo apt-get install pychecker

install:
  - pip install pybuilder
  - pyb install_dependencies

script: "pyb"

notifications:
  email:
  - akmehra@iu.edu
