FROM tomcat:7-jre8
ADD /target/StormExists.war /usr/local/tomcat/webapps/
#docker run -it --rm -p 8080:8080 -v /Users/akmehra/git/TeamFlash/StormCheck/target:/usr/local/tomcat/webapps/ --name StormCheck webserver
#docker run -it --rm -p 8080:8080 --name StormCheck webserver1
EXPOSE 8080